MOVED_LEFT = 'MOVED_LEFT'
MOVED_RIGHT = 'MOVED_RIGHT'
MOVED_UP = 'MOVED_UP'
MOVED_DOWN = 'MOVED_DOWN'
WAITED = 'WAITED'
INVALID_ACTION = 'INVALID_ACTION'

BOMB_DROPPED = 'BOMB_DROPPED'
BOMB_EXPLODED = 'BOMB_EXPLODED'

CRATE_DESTROYED = 'CRATE_DESTROYED'
COIN_FOUND = 'COIN_FOUND'
COIN_COLLECTED = 'COIN_COLLECTED'

KILLED_OPPONENT = 'KILLED_OPPONENT'
KILLED_SELF = 'KILLED_SELF'

GOT_KILLED = 'GOT_KILLED'
OPPONENT_ELIMINATED = 'OPPONENT_ELIMINATED'
SURVIVED_ROUND = 'SURVIVED_ROUND'

# own events

MOVED_TO_COIN = 'MOVED_TO_COIN'
MOVED_AWAY_FROM_COIN = 'MOVED_AWAY_FROM_COIN'

MOVED_TO_BOMB = 'MOVED_TO_BOMB'
MOVED_AWAY_FROM_BOMB = 'MOVED_AWAY_FROM_BOMB'

DODGED_BOMB = 'DODGED_BOMB'
ANTIDODGED_BOMB = 'ANTIDODGED_BOMB'

EDGE_BOMB = 'EDGE_BOMB'
SMART_BOMB = 'SMART_BOMB'
DUMB_BOMB = 'DUMB_BOMB'

DEAD_END = 'DEAD_END'
NOT_DEAD_END = 'NOT_DEAD_END'